### ISSUE TITLE
Lazy Symbol Binding Failed

### ISSUE THREAD

**Issue by AndyJahn** [trislett/TFCE_mediation#2]
Hello,

I recently installed the TFCE_mediation program, and installed the dependencies with pip. However, when I try to run this command:

`tfce_mediation step0-vertex -i subjListTFCE.txt area`

I get the following error:

`dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib`

And the rest of the command crashes. Do you have any insight into why this error is happening? I don't have that much experience with Python, so it may be something more elementary, but I was curious whether you've come across this situation before.

Best,

-Andy

**Comment by trislett** [comment]
Hi Andy,

I've never seen this error before, but it seems like it may be an issue with freesurfer (not necessarily TFCE_mediation). I have a few questions: 

Are you using OSX? Does freesurfer run correctly? Which version of freesurfer do you have?
Did you build TFCE_mediation from the source or did you install it using PIP?

What happens if you run command for a single subject? See below (rename "subject_id" to one of your subjects).

```
i=subject_id;
hemi=lh;
$FREESURFER_HOME/bin/mri_surf2surf --srcsubject ${i} --srchemi ${hemi} --srcsurfreg sphere.reg --trgsubject fsaverage --trghemi ${hemi} --trgsurfreg sphere.reg --tval ./${hemi}.${i}.area.00.mgh --sval ${SUBJECTS_DIR}/${i}/surf/${hemi}.area --jac --sfmt curv --noreshape --cortex;
```

Cheers,
Tris

Edit: this may be the issue [mountain-lion-dyld-lazy-symbol-binding-failed](https://stackoverflow.com/questions/22920497/git-mountain-lion-dyld-lazy-symbol-binding-failed-symbol-not-found-str)

**Comment by AndyJahn** [comment]
Hey Tris,

Thanks for the quick reply. I am using OSX, and freesurfer (version 6.0) works fine. I installed the TFCE_mediation toolbox from PIP. The command you gave me executed without errors.

I'll check the thread and see if that resolves the problem.


Thanks!

-Andy

**Comment by trislett** [comment]
Ok, there may to be an issue with OSX and mris_convert. This [post](https://afni.nimh.nih.gov/afni/community/board/read.php?1,154067,154113#msg-154113) from the afni forum discusses it. Here's another [thread](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg51655.html) on the issue. It is seems that the OSX doesn't allow access to /usr library directory unless SIPS is turned off. The instructions for turning off (and on) SIPS area [here](http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/). 

Please let me know if this works, and which version of OSX you are using.

**Comment by AndyJahn** [comment]
Hello Tris,

The issue was with SIP; once I turned it off, the commands worked.

Thanks!

-Andy

**Comment by trislett** [comment]
I'm glad it worked out for you.
Alternatively, you could have used geodesic smoothing instead of the fudge
factor. I think it was freesurfer's surface smoothing that was causing the
issue.
